api_platform:
    title: Selfcare B2B KM
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 10 # Default value
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        multipart: ['multipart/form-data']
        jsonld: ['application/ld+json']
        json: ['application/json']
        csv: ['text/csv']