
services:
  db:
    image: mariadb:11.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: selfcareKM
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: --local-infile=1
    ports:
      - "3307:3306"
    volumes:
      - db_data_project2:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  adminer:
      image: adminer
      restart: always
      ports:
        - "8083:8080"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: root
      MYSQL_PASSWORD:
      UPLOAD_LIMIT: 10000000M
  

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "PulseDev"
      LDAP_DOMAIN: "pulse.local"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d

volumes:
  db_data_project2:





