api_platform:
    resource: .
    type: api_platform
    prefix: /api

check_stock:
    path: /api/company/{action}/{id}
    controller: App\Controller\CompanyController::toggleStatus
    methods: [PUT]
