api_platform:
    resource: .
    type: api_platform
    prefix: /api

toggle_company:
    path: /api/company/{action}/{id}
    controller: App\Controller\CompanyController::toggleStatus
    methods: [PUT]

toggle_user:
    path: /api/user/{action}/{id}
    controller: App\Controller\UserController::toggleStatus
    methods: [PUT]

toggle_msisdn_fleet:
    path: /api/msisdnfleet/{action}/{id}
    controller: App\Controller\MsisdnController::toggleStatus
    methods: [PUT]


