# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc..

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        tags:
            - ldap
    
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            - host: '%env(resolve:LDAP_HOST)%'
              port: '%env(resolve:LDAP_PORT)%'
              encryption: none
              options:
                 protocol_version: 3
                 referrals: false
              debug:  false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Exception\Normalizer\:
        resource: '../src/Exception/Normalizer'
        tags: ['app.exception_normalizer']

    App\EventListener\ExceptionListener:
        arguments:
            $normalizers: !tagged_iterator 'app.exception_normalizer'

    App\OpenApi\CustomOpenApiCompanyFactory:
        decorates: 'api_platform.openapi.factory'

    App\OpenApi\CustomOpenApiUserFactory:
        decorates: 'api_platform.openapi.factory'

    App\OpenApi\CustomOpenApiMsisdnFleetFactory:
        decorates: 'api_platform.openapi.factory'

    App\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\OpenApi\OpenApiFactory.inner']

    App\Manager\UserManager: ~

    App\EventListener\MsisdnFleetDateListener:
        autowire: true
        autoconfigure: false
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: App\Entity\MsisdnFleet, method: prePersist }
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: App\Entity\MsisdnFleet, method: preUpdate }


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
